## 1.0
**Problem 1.** Consider the three mass-four spring system in figure below <img src="kuanyshbay_maksat_201512000_assign_04.png" width="400" height="100">
<br>Determining the equations of motion from $\sum F_x = ma$, for each mass using its free-body diagram results in the following differential equations:$$\begin{array}{l} a_1 + \frac{k_1+k_2}{m_1}x_1-\frac{k_2}{m_1}x_2=0 \\ 
a_2-\frac{k_2}{m_2}x_1+\frac{k_2+k_3}{m_2}x_2-\frac{k_3}{m_2}x_3=0 \\
a_3-\frac{k_3}{m_3}x_2+\frac{k_3+k_4}{m_3}x_3=0 \end{array} \tag{1}$$ where $k_1=k_4=10 \ N/m$, $k_2=k_3=30 \ N/m$, and $m_1=m_2=m_3=2$ kg. Write the three equations in matrix form: 
<br><br>$$[k/m \ \text{matrix}][\text{displacement vector} \ x] = [\text{Acceleration vector}] \tag{2}$$<br>
At a specific time where $a_1=0.1 \ m/s^2$, $a_2=0.3 \ m/s^2$, and $a_3=0.1 \ m/s^2$, this forms a tridiagonal system. Solve for the displacement of each mass using **your own python implementation of the Thomas's algorithm** for solving the tridiagonal systems of equations.

## 1.1
The matrix form of the equations:
<br>
$$\begin{bmatrix} -\frac{k_1+k_2}{m_1} & \frac{k_2}{m_1} & 0 \\ \frac{k_2}{m_2} & -\frac{k_2+k_3}{m_2} & \frac{k_3}{m_2} \\ 0 & \frac{k_3}{m_3} & -\frac{k_3+k_4}{m_3} \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} = \begin{bmatrix} a_1 \\ a_2 \\ a_3 \end{bmatrix} \tag{2.1}$$
(2.1) with substituted values:
<br>
$$\begin{bmatrix} -20 & 15 & 0 \\ 15 & -30 & 15 \\ 0 & 15 & -20 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} = \begin{bmatrix} 0.1 \\ 0.3 \\ 0.1\end{bmatrix} \tag{2.2}$$

In [1]:
#1.2
import numpy as np
def tom(A):                       #my own python implementation of the Thomas's algorithm
    n = np.shape(A)[0]
    d = np.zeros(n, float)        #array for the diagonal of the matrix
    d[n-1] = A[n-1,n-1]
    u = np.zeros(n-1, float)      #array for the upper diagonal of the matrix  
    l = np.zeros(n-1, float)      #array for the lower diagonal of the matrix 
    b = np.zeros(n, float)        #array for the last column of the matrix
    b[n-1] = A[n-1,n]
    x = np.zeros(n, float)
    
    for i in range(n-1):
        d[i] = A[i,i]
        u[i] = A[i, i+1]
        l[i] = A[i+1, i]
        b[i] = A[i,n]
        
    for i in range(n-1):
        d[i+1] = d[i+1] - u[i]*l[i]/d[i]
        b[i+1] = b[i+1] - b[i]*l[i]/d[i]
        
    x[n-1] = b[n-1]/d[n-1]
    
    for i in range(n-1):
        x[n-2-i] = (b[n-2-i] - u[n-2-i]*x[n-1-i])/d[n-2-i]
    
    return x

In [2]:
#1.3
A = np.matrix([[-20, 15, 0, 0.1], [15, -30, 15, 0.3], [0, 15, -20, 0.1]], float)
tom(A)

array([-0.05, -0.06, -0.05])

## 2.0
**Problem 2.**
<br>**a)** Implement the Cholesky factorization algorithm in python which is analogous to $LU$ factorization but applicable only for symmetric matrices. Compute the Cholesky factorization for the matrix $$A=\begin{bmatrix} 2 & 1 & 1 \\ 1 & 4 & 2 \\ 1 & 2 & 6\end{bmatrix} \tag{3}$$
**b)** The following system of equations is designed to determine concentrations (the c's in g/m$^3$) in a series of coupled reactors as a function of the amount of mass input to each reactor (the right-hand sides in g/day), $$\begin{array}{r} 15c_1 - 3c_2-c_3=3300 \\ 
-3c_1+18c_2-6c_3=1200 \\
-4c_1-c_2+12c_3=2400 \end{array} \tag{4}$$

Solve this problem with the Gauss-Seidel iteration method to $\varepsilon_S$ = 5%.

In [3]:
#2.1 part a)
def chlsk(A):                     #my own python implementation of the Cholesky factorization
    n = np.shape(A)[0]
    L = np.zeros(np.shape(A),float)
    
    for i in range(n):
        temp = 0.0
        
        for j in range(i):
            temp2 = 0.0
            for k in range(j):
                temp2 = temp2 + L[j, k]*L[i, k]
            L[i, j] = (A[i, j] - temp2)/L[j, j]
            temp = temp + L[i, j]**2
        
        L[i, i] = np.sqrt(A[i, i] - temp)
    
    return L

In [4]:
#2.2 part a)
A = np.matrix([[2, 1, 1], [1, 4, 2], [1, 2, 6]], float)
L = chlsk(A)
print(f'Matrix L: \n {L} \n')
print(f'Matrix multiplication of L\'s transpose and L: \n {np.matmul(np.transpose(L),L)}\n')

Matrix L: 
 [[1.41421356 0.         0.        ]
 [0.70710678 1.87082869 0.        ]
 [0.70710678 0.80178373 2.20389266]] 

Matrix multiplication of L's transpose and L: 
 [[3.         1.88982237 1.55838744]
 [1.88982237 4.14285714 1.76704527]
 [1.55838744 1.76704527 4.85714286]]



In [5]:
#2.3 part b)
def gsi(A, tol):                  #my own python implementation of the Gauss-Seidel iteration method
    n = np.shape(A)[0]
    x = np.zeros(n, float)
    xold = np.zeros(n, float)
    
    for i in range(10000):
        good = 0
        
        for j in range(n):
            xold[j] = x[j]
            x[j] = A[j, n]/A[j,j]
            
            for k in range(n):
                if (k == j):
                    continue
                x[j] = x[j] - A[j,k]*x[k]/A[j,j]
        
        for t in range(n):
            if (np.abs((x[t]-xold[t])/x[t])) >= tol/100:
                good = 1
                break
                
        if (good == 0):
            break
    return x

In [6]:
#2.4 part b)
C = np.matrix([[15, -3, -1, 3300], [-3, 18, -6, 1200], [-4, -1, 12, 2400]], float)
c = gsi(C, 5)
print(f'c_1 = {c[0]} \nc_2 = {c[1]} \nc_3 = {c[2]}')

c_1 = 283.7028230420921 
c_2 = 217.8033174275813 
c_3 = 312.71788413299583
